openapi: "3.0.1"
info:
  title: "Products Service"
  description: "This is the Products Service API"
  version: "2025-02-22T21:52:07Z"
servers:
- url: "https://nltfc4ux9h.execute-api.eu-west-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "dev"
paths:
  /products/{productId}:
    get:
      parameters:
      - name: "productId"
        in: "path"
        required: true
        schema:
          type: "string"
    options:
      parameters:
      - name: "productId"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "204":
          description: "204 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
  /:
    options:
      responses:
        "204":
          description: "204 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
  /products:
    get: {}
    options:
      responses:
        "204":
          description: "204 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
components: {}
