branch-defaults:
  default:
    environment: slavafv-bff-service-dev
    group_suffix: null
deploy:
  artifact: Dockerrun.aws.json
global:
  application_name: slavafv-bff-api
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
