branch-defaults:
  default:
    environment: slavafv-bff-service-dev
global:
  application_name: slavafv-bff-api
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: eu-west-1
  workspace_type: Application
